Fix billboards example on ubuntu 20.04
Shader compilation was giving the following error:
error C7533: global variable gl_FragColor is deprecated after version 120